### ISSUE TITLE
Extend ec2-bootstrap concurrency to host

### ISSUE THREAD

**Issue by phylake** [adobe-platform/porter#106]
@jfieber @gregoryfischer I'm interested in your thoughts on this one.

We could extend [`concurrent: true`](https://github.com/adobe-platform/porter/blob/master/docs/detailed_design/config-reference.md#concurrent) to the host and change how ec2-bootstrapping works a bit. Instead of writing to `/usr/bin/porter_bootstrap` directly porter could run these scripts and leverage knowledge of ordering constraints or lack thereof to increase the speed that ec2 initialization occurs

**Comment by jfieber** [comment]
I would enthusiastically support the ec2 hook contract being: output of hook is something porter can save in a file, chmod u+x, and then fork/exec, with appropriate environment variables and std{in,out,err}.  Generating a fragment of a shell script is brittle, and promotes unexpected cross-hook interactions.
