### ISSUE TITLE
haproxy default ciphers

### ISSUE THREAD

**Issue by phylake** [adobe-platform/porter#173]
[Mozilla recommended config](https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations)

[ELB security policy](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html)

```
global
  ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
```

**Comment by phylake** [comment]
@spiess-adobe please advise on which ciphersuites should be used

**Comment by phylake** [comment]
I didn't see a Mozilla recommendation that matched up with ELB's default security policy

**Comment by spiess-adobe** [comment]
Given Porter is designed for AWS-based deployments, my recommendation is to go with the latest default ELB SSL security policy's set of cipher suites.  This should provide greater consistency.

If there are individual consumers of Porter that find this doesn't meet their needs, then perhaps the default is to use the equivalent of the ELB policy but have the ability to override that via a config that specifies an alternative preferred set of ciphers.
