### ISSUE TITLE
Need support for  instance type c5*

### ISSUE THREAD

**Issue by ranjansumit** [adobe-platform/porter#186]
We have noticed that there is huge saving associated with the current generation of EC2 instances.
For eg:- 

   Pricing for C3.2xlarge is $0.42/hour
   Pricing for c5.2xlarge is $0.34/hour

https://aws.amazon.com/ec2/pricing/on-demand/
https://aws.amazon.com/ec2/previous-generation/

Please add the support for c5* instance type in AWS.

**Comment by phylake** [comment]
Hi @ranjansumit I'll do this next week

**Comment by ranjansumit** [comment]
Thanks @phylake for the quick response.
