### ISSUE TITLE
Need support for 21 letter vpc id and 24 letter subnet id.

### ISSUE THREAD

**Issue by gpradhan909** [adobe-platform/porter#189]
AWS has recently made the change in the vpc id and subnet id format. Amazon EC2 has migrated to longer format, 17-character resource IDs.

Therefore the current VPC ID is 21 character long. (with 17 character resource Id and four characters for 'vpc-').
Similarly, the Subnet id is also upgraded to 24 character long.

The support for older format (8-character resource IDs) will continue.

Current porter version does not support new resource id format regex, can you please add the support.

**Comment by gpradhan909** [comment]
Can someone please support with this issue. This is urgently needed.

**Comment by phylake** [comment]
@gpradhan909 
> AWS has recently made the change in the vpc id and subnet id format

Can you share a link for this? I want to make sure I alter the regex to match

**Comment by gpradhan909** [comment]
@phylake 
These are the two links I can find:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html
https://aws.amazon.com/blogs/compute/longer-resource-ids-in-2018-for-amazon-ec2-amazon-ebs-and-amazon-vpc/

**Comment by phylake** [comment]
https://github.com/adobe-platform/porter/releases/tag/v5.2.2
