### ISSUE TITLE
Give more control over `docker build`

### ISSUE THREAD

**Issue by phylake** [adobe-platform/porter#32]
In particular services want to use `--build-arg` introduced in docker 1.9

The mechanism should be done once to enable ongoing adoption of build-time arguments, not done once for `--build-arg` and then repeated for all build-time arguments services want to use

**Comment by atulj** [comment]
Is this something we need to support in Ethos (Orca/Jenkins) too?

**Comment by phylake** [comment]
@atulj To quote @iderdik 

> It’s done entirely in the Jenkins job
> But those types of build secrets are something that we shoud be storing in DynamoDb
> and Jenkins will pull when it runs the job
> Orca will/should have an `upload build secrets` step to populate those values
