### ISSUE TITLE
Make provisioning more resilient to single-region provision failures

### ISSUE THREAD

**Issue by marckubischta** [adobe-platform/porter#34]
I'm assuming CloudFormation wait conditions are used for stack creation timeouts. But we are frequently seeing stack creation time vary wildly between different regions, e.g. two regions will complete in 15 minutes and the third will timeout after 30 minutes. When this occurs multiple times in a row, I start to feel as though there must be a better way to get new stacks provisioned.

Would it be possible to modify the provisioning to pass some large value for the CloudFormation wait condition, and then poll the stack creation status; and when a majority of regions complete before some timeout A, repeatedly retry provisioning the failing regions until a second timeout B?

**Comment by phylake** [comment]
@marckubischta There is a way to configure stack creation timeout. From `porter help debug`

> STACK_CREATION_TIMEOUT
> Override rollback time with a string parsed by
> https://golang.org/pkg/time/#ParseDuration
> 
> This is clamped to the min and max duration supported by STS AssumeRole
> 
> Example:
> export STACK_CREATION_TIMEOUT=1h
> porter create-stack -e dev

Let me know if that will suffice

**Comment by phylake** [comment]
@marckubischta bump

**Comment by marckubischta** [comment]
I think you misunderstood my scenario. I'm not looking to just increase the timeout; I still want to have stack creation time out after 30m. What I am asking for is a way to detect when the majority of regions have successfully provisioned, and in this case, re-run the provisioning for the failed regions.

**Comment by jfieber** [comment]
I think the distinction between is between
1. region A completes in 10 minutes, region B completes in 20 minutes, neither have any anomalies other than one taking a long time. A timeout to encompass the longer time is sufficient. 
2. Region A completes in 10 minutes, region B encounters some issue, where the stack will never complete but will only fail when it hits a timeout. Lengthening the timeout is not helpful if the stack is stalled. The incomplete stack is torn down and a retry deploy is a noop on region A, and region B gets a new deploy attempt. 

Ideally we would be able to detect the situations where a given stack is a lost cause and cancel the creation as early as possible. That seems like a pretty difficult problem though which makes Marc suggestion of interest, even though It is far from elegant. 

Reflecting on the most common stall scenarios, what would be more helpful is a timeout on getting a complete signal from an individual instance and aggressively terminate those that fail to bootstrap. I'm not sure porter has the necessary visibility to do that though. At least not trivially.

**Comment by phylake** [comment]
> Ideally we would be able to detect the situations where a given stack is a lost cause

Agreed but there's no way for porter to know if the failure was legitimate or not. I think at best it could see a majority succeeded and perform the retry as long as `sts token expiration / stack creation timeout < retry count`, otherwise porter will fail to poll for stack events during a retry that exceeds sts token expiration.

I tend to favor failing fast over retrying in this scenario. #22 will address this issue much better in the long term by bypassing CloudFormation altogether.
