### ISSUE TITLE
Multi-container deployment

### ISSUE THREAD

**Issue by phylake** [adobe-platform/porter#9]
This allows services to define more than one container to be deployed to an EC2 host.

This refers to managing a single instance of the different types of containers (i.e. adding support for container topologies `worker` and `cron`), not the number of each type #8 

Adds `dockerfile_path` and `dockerfile_build_path` to config

**Comment by svarma123** [comment]
+1

**Comment by chrzimme** [comment]
@phylake - Brandon, what is the time frame for this to be implemented? Asking since this was a support request for the Oz team in this https://git.corp.adobe.com/adobe-platform/sos/issues/35

**Comment by phylake** [comment]
@chrzimme Oct 31 based on the original conversation with the Oz team. For future reference you can see the due date on the milestone by clicking on it. Let me know if that date needs to be revised.

**Comment by atulj** [comment]
@phylake We are not supporting multiple containers in Ethos yet. OrCA only accepts single container. Is this request for porter only? But, if porter supports it, Ethos may need to do the same too.

**Comment by johnleetran** [comment]
@phylake 

For Oz, we have essentially 3 process that needs to be running for our application to work.  Ngnix, Unicorn, and MongoS.  We have a workaround for this by baking in all 3 processes in one docker image and running them all in one container...but that doesn't correspond to Docker best practice and breaks container isolation to some extent.

**Comment by atulj** [comment]
Marathon framework does not support linked containers. It is difficult to manage linked containers in terms of health check and difficult to provide robust fault tolerance in multi-tenant clusters. 
So, the best option in Ethos will be to run nginx + unicorn + mongos in one container. You can run a supervisor service (Docker supervisor - https://docs.docker.com/engine/admin/using_supervisord/) which can manage internal processes. 
/cc @bryanlatten

**Comment by bryanlatten** [comment]
@johnleetran documenting here from our Slack conversation. For 1st deployment, I would heavily advise to walk before we run - a single container per http-enabled service, not hard-limiting to a single process per container. While the process per container is an aspirational goal, it comes with more than a few caveats. Linked containers inherently have a wider fault domain - each linked container that fails require the full stack to restart. In addition, in a linked model, the services do _not_ scale or deploy independently, primary motivations for doing this.

**Comment by phylake** [comment]
As of #62 there is now support for worker-only topologies (CloudFormation w/o an ELB) and worker containers running inside an inet topology. The outstanding items are
- support for cron containers
- inter-container communication

This is not yet released. Once I get inter-container communication I'll release v2.1

**Comment by johnleetran** [comment]
@atulj @bryanlatten I agree that linked containers are inherently difficult to maintain fault tolerance and bad.  However, what about docker networking features that allows for the creation of an overlay network.  With an overlay network we can communicate with containers within the group that are spread out across different servers.  We can specify a docker network inside the spec file for each group, thus still providing fault tolerance in multi-tenant clusters.  

Yes, baby steps and we have baked in all necessary processes in a single docker container and successfully deployed using porter and moonbeam to production.

**Comment by atulj** [comment]
Unfortunately Mesos frameworks (Marathon etc) do not support it yet.

**Comment by bryanlatten** [comment]
@johnleetran for that type of deployment, you would require dynamic service discovery per-app to figure out where that networked service is, which is a bit of complexity we hope to avoid in these early days. For internal services, dynamic discovery sounds a lot like internal load balancer. There is a known degradation path and updates are possible by blue/green-ing traffic through them.

**Comment by phylake** [comment]
broke out #120 and #121
